meta_product_name: "brunchee."
meta_title: "brunchee. - Rocks"
meta_description: "The best place to find a brunch venue today!"
meta_image: "cover.jpeg" # should exist in `app/assets/images/`
twitter_account: "@brunchee"   # required for Twitter Cards
